---
name: '🚧 Package Build and Test'
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - 'src/**'
env:
  GO_VERSION: 1.18.6

jobs:
  build:
    runs-on:
      - self-hosted
      - lightning
    steps:
      - name: '🛒 Checkout Source Control'
        uses: actions/checkout@v3
      - name: '🛠 Setup Golang'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: '🏗 Build Package'
        run: |
          make build
      - name: '🚜 Run Tests'
        run: |
          make test
      - name: '🐳 Build Docker Image'
        run: |
          make docker-image
